[build]
  command = "./scripts/netlify-build.sh"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"

[context.dev.environment]
  JEKYLL_ENV = "staging"
